version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./code:/var/www/html
      - ./config/:/etc/nginx/conf.d/
    depends_on:
      - php-fpm

  php-fpm:
    build: .
    volumes:
      - ./code:/var/www/html
